[package]
name = "rust-riscv-benches"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
embedded-hal-nb = "1.0.0"
nb = "1.0.0"
riscv = "0.11.0"
spin = { version = "0.9.8", default-features = false, features = [
    "lazy",
    "spin_mutex"
] }
static_assertions = "1.1.0"
# staticvec = { version = "0.11.9", default-features = false }
volatile = "0.5.1"

[build-dependencies]
cc = "1.0.77"

[profile.release]
opt-level="z"
lto = true

#overflow-checks = true
#debug-assertions = true
[features]
default = ["unicode", "uart_sifive_u"]
unicode = []
uart_sifive_u = []

[dev-dependencies]
