[build]
target = "riscv64-custom.json"

[target."riscv64-custom"]
runner = "qemu-system-riscv64 -machine sifive_u -cpu rv64 -m 256M -bios none -display none -serial stdio -kernel"

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]
